blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://github.com/Tommy-Raven/sswg-mvm/tree/main/docs
    about: Review the internal documentation before submitting an issue.

  - name: ðŸ’¬ Not an Issue?
    url: https://github.com/Tommy-Raven/sswg-mvm/discussions
    about: Use Discussions for questions, ideas, or examples that are not bug reports.
