name: "Sync Repo & Project Description"

on:
  push:
    branches: [ "main" ]
    paths:
      - "DESCRIPTION.txt"

permissions:
  contents: read

jobs:
  update_description:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: ðŸ”‘ Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh auth setup-git

      - name: ðŸª¶ Update repository About section
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          DESC=$(cat DESCRIPTION.txt)
          gh repo edit ${{ github.repository }} \
            --description "$(head -n 1 DESCRIPTION.txt)" \
            --homepage "https://github.com/users/Tommy-Raven/projects/1"
